import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:edulink/l10n/app_localizations.dart';
import 'app/router.dart';
import 'core/firebase/firebase_refs.dart';
import 'core/notifications/push_service.dart';
import 'core/purchases/purchase_service.dart';
import 'features/auth/models/app_user.dart';
import 'features/auth/providers/auth_controller.dart';
import 'core/theme/app_theme.dart';
// Generated by `flutterfire configure` (gitignored). Run that command from the
// `mobile/` directory before the first build, or this import will not resolve.
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // App Check attests that calls to our backend come from the genuine app.
  // Debug provider on simulators/dev builds (register the printed debug token in
  // the Firebase console); App Attest / Play Integrity in release.
  await FirebaseAppCheck.instance.activate(
    appleProvider:
        kDebugMode ? AppleProvider.debug : AppleProvider.appAttest,
    androidProvider:
        kDebugMode ? AndroidProvider.debug : AndroidProvider.playIntegrity,
  );
  // RevenueCat. A no-op until the SDK keys are supplied via
  // --dart-define-from-file, so the app runs fine without them.
  await PurchaseService.configure(Fb.auth.currentUser?.uid);

  runApp(const ProviderScope(child: EduLinkApp()));
}

class EduLinkApp extends ConsumerWidget {
  const EduLinkApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Register this device for push once a user is signed in with a role. Done
    // here because auth state is already the app-wide source of truth.
    ref.listen<AsyncValue<AppUser?>>(authStateProvider, (previous, next) {
      final user = next.valueOrNull;
      if (user == null || !user.hasRole) return;
      if (previous?.valueOrNull?.uid == user.uid) return; // already registered
      pushService.registerForUser(user.uid);
      // A purchase is tied to the RevenueCat `app_user_id`, which must BE the
      // Firebase uid — it is the only thing linking money taken by Apple to an
      // account of ours. Re-identify on every sign-in, or a purchase lands on an
      // anonymous id that belongs to nobody.
      PurchaseService.identify(user.uid);
    });
    // Covers the already-signed-in case on a cold start, which `listen` alone
    // would miss (it only fires on subsequent changes).
    final current = ref.watch(authStateProvider).valueOrNull;
    if (current != null && current.hasRole) {
      pushService.registerForUser(current.uid);
    }

    return MaterialApp.router(
      title: 'EduLinky',
      theme: AppTheme.light,
      routerConfig: ref.watch(goRouterProvider),
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
      ],
    );
  }
}
